// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace FPAuth
{
    public static class GPSids
    {
        public const string achievement_3 = "CgkIkN632ZAWEAIQCA";
        // <GPGSID>
        public const string achievement_win_a_game_with_a_deck_you_built = "CgkIkN632ZAWEAIQEA";
        // <GPGSID>
        public const string achievement_5 = "CgkIkN632ZAWEAIQCg";
        // <GPGSID>
        public const string achievement_buy_a_level_on_a_card = "CgkIkN632ZAWEAIQDw";
        // <GPGSID>
        public const string achievement_4 = "CgkIkN632ZAWEAIQCQ";
        // <GPGSID>
        public const string achievement_complete_a_realm = "CgkIkN632ZAWEAIQEg";
        // <GPGSID>
        public const string achievement_open_an_ultimate_card = "CgkIkN632ZAWEAIQEw";
        // <GPGSID>
        public const string achievement_add_a_card_to_your_collection = "CgkIkN632ZAWEAIQDg";
        // <GPGSID>
        public const string achievement_use_a_super_spin = "CgkIkN632ZAWEAIQEQ";
        // <GPGSID>
        public const string achievement_1 = "CgkIkN632ZAWEAIQBg";
        // <GPGSID>
        public const string achievement_2 = "CgkIkN632ZAWEAIQBw";
        // <GPGSID>

    }
}
